# Custom Language File for Launcher Customizer

[ejs.app]
title = "Everland Launcher"

[ejs.landing]
mediaGitHubURL = ""
mediaTwitterURL = ""
mediaInstagramURL = ""
mediaYouTubeURL = ""
mediaDiscordURL = ""

[ejs.settings]
sourceGithubLink = "https://github.com/Limbo-Studios/EverlandLauncher"
supportLink = "https://github.com/Limbo-Studios/EverlandLauncher/issues"
selectLanguage = "Select a Language"
changeLanguageTitle = "Change the launcher language"
changeLanguageDesc = "You can change the language in the list below. This text will not change if you change the language so you can find your wayback here to change it back"

[ejs.welcome]
welcomeHeader = "BIENVENIDOS AL LAUNCHER DE EVERLAND"
welcomeDescription = "Esperamos disfrutes tu estancia ;)"

[ejs.overlay]
changedLanguageHeader = "You changed the previous language"
