# Custom Language File for Launcher Customizer

[ejs.app]
title = "Limbo Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Limbo-Studios/LimboLauncher"
mediaTwitterURL = "https://twitter.com/lurkarya"
mediaInstagramURL = ""
mediaYouTubeURL = "https://www.youtube.com/@Vigilante_LK"
mediaDiscordURL = ""

[ejs.settings]
sourceGithubLink = "https://github.com/Limbo-Studios/LimboLauncher"
supportLink = "https://github.com/Limbo-Studios/LimboLauncher/issues"
selectLanguage = "Select a Language"
changeLanguageTitle = "Change the launcher language"
changeLanguageDesc = "You can change the language in the list below. This text will not change if you change the language so you can find your wayback here to change it back"

[ejs.welcome]
welcomeHeader = "WELCOME TO LIMBO LAUNCHER"
welcomeDescription = "We have created this launcher so you can enjoy our projects, the ongoing project for now is Lurkarya, but you can always keep an eye out for more! Lurkarya is a multiplayer survival server with lore, now we are in the second act and we can't wait to see what fate has in store for y'all ;).<br><br><center> You can change the launcher language in Settings --> Launcher"

[ejs.overlay]
changedLanguageHeader = "You changed the previous language"
